version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: odfe-node1
    environment:
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # minimuIm and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
      - /opt/open/es_deploy/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - /opt/open/es_deploy/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/open/es_deploy/cert/node.pem:/usr/share/elasticsearch/config/node.pem
      - /opt/open/es_deploy/cert/node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - /opt/open/es_deploy/cert/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://odfe-node1:9200
      ELASTICSEARCH_HOSTS: http://odfe-node1:9200
      #ELASTICSEARCH_USERNAME: admin
      ELASTICSEARCH_USERNAME: kibanaserver
      #ELASTICSEARCH_PASSWORD: ou4d8RY7%es1a58
      ELASTICSEARCH_PASSWORD: 514IFvw5EYAEs3m%
    networks:
      - odfe-net

volumes:
  odfe-data2:

networks:
  odfe-net:
